#!/usr/bin/env zsh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
EXTERNAL_DIR="${ROOT_DIR}/token-service/external-tokens"
DIST_SCSS_DIR="${EXTERNAL_DIR}/packages/tokens/dist/scss"
TARGET_SCSS_DIR="${ROOT_DIR}/src/scss/base"

echo "[sync-external-tokens] External tokens dir: ${EXTERNAL_DIR}"

if [ ! -d "${EXTERNAL_DIR}" ]; then
  echo "External tokens submodule not found at ${EXTERNAL_DIR}" >&2
  exit 1
fi

if [ ! -d "${DIST_SCSS_DIR}" ]; then
  echo "Dist SCSS directory not found (expected built tokens): ${DIST_SCSS_DIR}" >&2
  echo "Run build in external tokens repo: (cd token-service/external-tokens/packages/tokens && npm install && npm run compile)" >&2
  exit 2
fi

mkdir -p "${TARGET_SCSS_DIR}" || true

echo "Copying SCSS token artifacts..."
rsync -a --delete "${DIST_SCSS_DIR}/" "${TARGET_SCSS_DIR}/external-tokens/"

echo "Generating aggregator _external-tokens.scss file..."
AGG_FILE="${TARGET_SCSS_DIR}/_external-tokens.scss"
cat > "${AGG_FILE}" <<'EOF'
// Generated by sync-external-tokens.sh - do not edit directly
// Aggregates external token SCSS for easy import
@forward "external-tokens/global";
@use "external-tokens/global" as *;
// Theme mixin initialization (if provided by external tokens build)
@mixin dls-init-themes() {
  @include initialize();
}
EOF

echo "Done. Import with: @import 'base/external-tokens';"