image: registry.web.boeing.com/container/images/stack/ubi9minimal-node18:9.2-750-1-2

stages:
  - build
  - deploy

build-package:
  stage: build
  only: 
    - release
  script:
    # Add Figma Environment variables
    - echo "FIGMA_API_KEY=${FIGMA_API_KEY}" > .env
    - echo "FIGMA_ICONS_FILE_KEY=${FIGMA_ICONS_FILE_KEY}" >> .env
    # Build tokens - commented out generation of scss files so that themeMixin.scss is uneffected
    - cd token-service
    - echo "registry=https://${JFROG_URL}/${JFROG_REPO}/" > .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:_password=${JFROG_PASSWORD}" >> .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:username=${JFROG_USER}" >> .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:always-auth=true" >> .npmrc
    - echo "Created the following .npmrc:"; cat .npmrc
    - npm install
    - npm run ts
    # https://api.figma.com/v1/files/ is returning a 404, so disabling icon generation for now
    #- npm run icons
    # Build assets
    - cd ..
    - echo "registry=https://${JFROG_URL}/${JFROG_REPO}/" > .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:_password=${JFROG_PASSWORD}" >> .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:username=${JFROG_USER}" >> .npmrc
    - echo "//${JFROG_URL}/${JFROG_REPO}/:always-auth=true" >> .npmrc
    - echo "Created the following .npmrc:"; cat .npmrc
    - npm install
    - npm run release
  artifacts:
    paths:
      - dist/

publish-npm:
  stage: deploy
  only: 
    - release
  script:
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    # Extract a few values from package.json
    - NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")
    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - echo "Created the following .npmrc:"; cat .npmrc

    # Validate that the package name is properly scoped to the project's root namespace.
    # For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#package-naming-convention
    - |
      if [[ ! $NPM_PACKAGE_NAME =~ ^@$CI_PROJECT_ROOT_NAMESPACE/ ]]; then
        echo "Invalid package scope! Packages must be scoped in the root namespace of the project, e.g. \"@${CI_PROJECT_ROOT_NAMESPACE}/${CI_PROJECT_NAME}\""
        echo 'For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#package-naming-convention'
        exit 1
      fi

    # Compare the version in package.json to all published versions.
    # If the package.json version has not yet been published, run `npm publish`.
    # If $SIGSTORE_ID_TOKEN is set this template will generate a provenance
    # document. For more information refer to the documentation: https://docs.gitlab.com/ee/ci/yaml/signing_examples/
    - |
      if [[ "$(npm view ${NPM_PACKAGE_NAME} versions)" != *"'${NPM_PACKAGE_VERSION}'"* ]]; then
        if [[ -n "${SIGSTORE_ID_TOKEN}" ]]; then
          npm publish --provenance
        else
          npm publish
        fi
        echo "Successfully published version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME} to GitLab's NPM registry: ${CI_PROJECT_URL}/-/packages"
      else
        echo "Version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME} has already been published, so no new version has been published."
      fi
