name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'

# Remove before going to prod
concurrency:
  group: release-workflow
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies and build tokens
        run: |
          cd token-service
          echo "FIGMA_API_KEY=${{ secrets.FIGMA_API_KEY }}" > .env
          echo "FIGMA_ICONS_FILE_KEY=${{ vars.FIGMA_ICONS_FILE_KEY }}" >> .env
          npm install
          npm run ts
          npm run icons
          cd ..

      - name: Build assets
        run: |
          npm install
          npm run release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Extract package info
        id: package_info
        run: |
          NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")
          NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "NPM_PACKAGE_NAME=$NPM_PACKAGE_NAME" >> $GITHUB_ENV
          echo "NPM_PACKAGE_VERSION=$NPM_PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Publish to GitHub Packages
        run: |
          npm publish
          echo "Successfully published version $NPM_PACKAGE_VERSION of $NPM_PACKAGE_NAME to GitHub Packages"
